TARGET = CW310

SRC += cdce906.c naeusb/circbuffer.c fpgaspi_program.c fpgautil_io.c main_cw310.c naeusb_bergen.c
SRC += tasks.c thermal_power.c timers.c tps56520.c 

SRC += naeusb/circbuffer.c naeusb/udc.c naeusb/naeusb.c naeusb/naeusb_default.c naeusb/naeusb_usart.c naeusb/naeusb_mpsse.c naeusb/naeusb_fpga_target.c
SRC += naeusb/usb_xmem.c naeusb/fpga_program.c

LINKERFILE = naeusb/flash_sam3x8.ld

include naeusb/makefile.cw