TARGET = CW340

SRC += naeusb/circbuffer.c fpgautil_io.c main_cw340.c naeusb_bergen.c naeusb_luna.c
SRC += tasks.c thermal_power.c timers.c  usbc_pd.c

SRC += naeusb/circbuffer.c naeusb/udc.c naeusb/naeusb.c naeusb/naeusb_default.c naeusb/naeusb_usart.c naeusb/naeusb_fpga_target.c
SRC += naeusb/fpga_selectmap.c
SRC += naeusb/usb_xmem.c naeusb/fpga_program.c naeusb/fpgaspi_program.c naeusb/tps56520.c naeusb/cdce906.c

LINKERFILE = naeusb/flash_sam3x8.ld

include naeusb/makefile.cw